# Generated by Django 2.2.12 on 2020-11-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pasien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_pasien', models.CharField(max_length=10, null=True)),
                ('nama_pasien', models.CharField(max_length=240, null=True)),
                ('jenis_kelamin', models.CharField(max_length=6, null=True)),
                ('alamat_pasien', models.CharField(max_length=100, null=True)),
                ('no_hp', models.IntegerField(null=True)),
            ],
        ),
    ]
