# Generated by Django 2.2.12 on 2020-11-02 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0007_auto_20201102_0657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='online',
            old_name='jumlah',
            new_name='jumlah_barang',
        ),
        migrations.RenameField(
            model_name='online',
            old_name='alamat_pemesan',
            new_name='nama_toko',
        ),
        migrations.RenameField(
            model_name='online',
            old_name='ukuran',
            new_name='ukuran_barang',
        ),
        migrations.RemoveField(
            model_name='online',
            name='nama_pemesan',
        ),
    ]
