# Generated by Django 2.2.12 on 2020-11-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='online',
            name='nama_toko',
        ),
        migrations.AddField(
            model_name='online',
            name='nama',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='online',
            name='total_pembayaran',
            field=models.IntegerField(null=True),
        ),
    ]
