# Generated by Django 2.2.12 on 2020-11-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi', '0002_auto_20201104_0649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='online',
            old_name='jumlah_barang',
            new_name='jumlah_pemesanan',
        ),
        migrations.RemoveField(
            model_name='online',
            name='nama',
        ),
        migrations.RemoveField(
            model_name='online',
            name='total_pembayaran',
        ),
        migrations.AddField(
            model_name='online',
            name='alamat_pemesan',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='online',
            name='nama_pemesan',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
