# Generated by Django 2.2.12 on 2020-11-05 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi', '0003_auto_20201104_0724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='online',
            name='nomor_id',
        ),
    ]
