# Generated by Django 3.1.2 on 2020-10-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Online',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_id', models.IntegerField(null=True, unique=True)),
                ('nama_barang', models.CharField(max_length=240, null=True)),
                ('ukuran', models.CharField(max_length=6, null=True)),
                ('nama_pemesan', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
