# Generated by Django 3.1.2 on 2020-10-29 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokoonline', '0002_auto_20201028_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='online',
            name='alamat_pemesan',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
