# Generated by Django 3.1.2 on 2020-10-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokoonline', '0003_online_alamat_pemesan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='online',
            name='nomor_id',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
