# Generated by Django 2.2.12 on 2020-11-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Online',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_id', models.CharField(max_length=5, null=True)),
                ('nama_barang', models.CharField(max_length=240, null=True)),
                ('ukuran', models.CharField(max_length=6, null=True)),
                ('nama_pemesan', models.CharField(max_length=100, null=True)),
                ('alamat_pemesan', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
