# Generated by Django 2.2.12 on 2020-11-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembeli', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='online',
            name='jumlah_pemesanan',
            field=models.IntegerField(null=True),
        ),
    ]
