# Generated by Django 2.2.12 on 2020-11-02 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pembeli', '0002_online_jumlah_pemesanan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='online',
            old_name='ukuran',
            new_name='ukuran_barang',
        ),
    ]
