# Generated by Django 2.2.12 on 2020-11-02 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pembeli', '0003_auto_20201102_0801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='online',
            name='alamat_pemesan',
        ),
    ]
