# Generated by Django 2.2.12 on 2020-11-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembeli', '0004_remove_online_alamat_pemesan'),
    ]

    operations = [
        migrations.AddField(
            model_name='online',
            name='alamat_pemesan',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
