# Generated by Django 2.2.12 on 2020-11-05 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pembeli', '0005_online_alamat_pemesan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='online',
            name='nomor_id',
        ),
    ]
